// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iunqfdwarvpgrjgjhqaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1bnFmZHdhcnZwZ3JqZ2pocWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDc3MDIsImV4cCI6MjA2OTA4MzcwMn0.5VdlcDIA3NpqaDq2YM9epEw07nqlRanyG0YdmyWnxdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});